export const images = {
  Strategy: require("./strategy.jpg"),
  Fps: require("./fps.jpg"),
  Rpg: require("./rpg.jpg"),
  Puzzle: require("./puzzle.jpg"),
  RolePlaying: require("./role-playing.jpg"),
  Sports: require("./sport.jpg"),
  Minecraft: require("./minecraft.jpg"),
  Asphalt: require("./asphalt.jpg"),
  Witcher: require("./witcher.jpg"),
  SurvingMars: require("./surviving-mars.jpg"),
  Gta5: require("./gta5.jpg"),
  roblox: require("./roblox.jpg"),
  Nba: require("./nba.jpg"),
  Dbd: require("./dbd.jpg"),
  Ark: require("./ark.jpg"),
  RocketLeague: require("./rocket-league.jpg"),
  Forza: require("./forza.jpg"),
  Cities: require("./cities.jpg"),
  Cod: require("./cod.png"),
  Nba2k22: require("./nba-2k22.png"),
  Fifa: require("./fifa.png"),
  ResidentEvil: require("./resident-evil-4.png"),
  Alien: require("./alien.png"),
  User1: require("./user1.jpg"),
  User2: require("./user2.jpg"),
  User3: require("./user3.jpg"),
};
